### ISSUE TITLE
Chart gridlines extend beyond the scope of the chart components

### ISSUE THREAD

**Issue by jufemaiz** [COzero/nvd3#19]
<img width="1368" alt="screenshot 2018-05-24 08 08 52" src="https://user-images.githubusercontent.com/16481/40455987-3f9daed8-5f2a-11e8-981f-565761303aba.png">

See the arrows.

**Comment by jeznag** [comment]
![image](https://user-images.githubusercontent.com/1034890/40460124-8e617b76-5f48-11e8-9f87-8e690cddebda.png)

Fixed in https://github.com/COzero/nvd3/pull/18/commits/6474d0ce8fae5da95e44e62fbaa9f172cf5c4ace
